language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install -r requirements_test.txt
  - pip install -e .
matrix:
  include:
    - python: 3.7
      dist: xenial  # required for Python 3.7 (travis-ci/travis-ci#9069)
      sudo: true    # required for Python 3.7 (travis-ci/travis-ci#9069)
script:
  - pytest tests
